version: '2'
services:
  haproxy:
    image: haproxy:alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "1080:1080"
      - "5672:5672"
      - "10800:10800"
    depends_on:
      - rabbit1
      - rabbit2
      - rabbit3

  rabbit1:
    image: bijukunjummen/rabbitmq-server:3.6.10
    hostname: rabbit1
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  rabbit2:
    image: bijukunjummen/rabbitmq-server:3.6.10
    hostname: rabbit2
    links:
      - rabbit1
    environment:
     - CLUSTERED=true
     - CLUSTER_WITH=rabbit1
     - RAM_NODE=true
    ports:
        - "5674:5672"
        - "15673:15672"

  rabbit3:
    image: bijukunjummen/rabbitmq-server:3.6.10
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment:
     - CLUSTERED=true
     - CLUSTER_WITH=rabbit1
    ports:
        - "5675:5672"
        - "15674:15672"

# docker exec rabbitmq_rabbit1_1 rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
